#264 null pointer exception
jenkinsci/gitlab-branch-source-plugin pull request #391
Opened 2024-01-27 18:22 UTC by rhit-gawronja

### Testing done
Completed reproduction steps before and after, passed automatic testing coverage. Where these fixes differ is when you have an archived project  previously it would cause a NullPointerException in the scanning process. This issue has been remediated by skipping over null projects in the scanning. Issue link: [https://github.com/jenkinsci/gitlab-branch-source-plugin/issues/264](url)

```[tasklist]
### Submitter checklist
- [ x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ x] Ensure that the pull request title represents the desired changelog entry
- [ x] Please describe what you did
- [ x] Link to relevant issues in GitHub or Jira
- [ x] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

2024-01-29 02:23 UTC, UltimateGeek reviewed
I recommend not adding extra comments above the functions that don't provide any more information than the name of the function already provides.

2024-01-29 02:23 UTC, UltimateGeek commented on src/test/java/io/jenkins/plugins/gitlabbranchsource/GitLabHookCreatorParameterizedTest.java
> +ackage io.jenkins.plugins.gitlabbranchsource;
Need to revert this change

```suggestion
package io.jenkins.plugins.gitlabbranchsource;
```

2024-01-29 02:23 UTC, UltimateGeek commented on src/test/java/io/jenkins/plugins/gitlabbranchsource/.GitLabHookCreatorParameterizedTest.java.~undo-tree~
> +nil
remove this file

2024-01-29 02:23 UTC, UltimateGeek commented on src/main/java/io/jenkins/plugins/gitlabbranchsource/.GitLabSCMNavigator.java.~undo-tree~
remove this file

2024-01-31 14:19 UTC, rhit-gawronja commented on src/test/java/io/jenkins/plugins/gitlabbranchsource/GitLabHookCreatorParameterizedTest.java
> +ackage io.jenkins.plugins.gitlabbranchsource;
Done, thanks for the feedback

2024-01-31 14:20 UTC, rhit-gawronja commented on src/test/java/io/jenkins/plugins/gitlabbranchsource/.GitLabHookCreatorParameterizedTest.java.~undo-tree~
> +nil
Done, thanks for the feedback

2024-01-31 14:20 UTC, rhit-gawronja commented on src/main/java/io/jenkins/plugins/gitlabbranchsource/.GitLabSCMNavigator.java.~undo-tree~
Done, thanks for the feedback

2024-01-31 19:43 UTC, rhit-gawronja commented
#264   Small fix for this issue

2024-02-10 12:15 UTC, jetersen commented on src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabSCMNavigator.java
> +                }
Loose the println and simply filter them.

```suggestion
            projects = projects.stream().filter(Objects::nonNull).collect(Collectors.toList());
            for (Project p : projects) {
                count++;
```

2024-03-05 05:17 UTC, jetersen requested changes

2024-03-05 05:17 UTC, jetersen commented on src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabSCMNavigator.java
> +    // gets the owner of the gitlab
```suggestion
```

2024-03-05 05:17 UTC, jetersen commented on src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabSCMNavigator.java
> +    // this checks all of our project source files
```suggestion
```

2024-03-05 05:17 UTC, jetersen commented on src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabSCMNavigator.java
> +            // we may check with web hooks but we don't check if the projects returned are null
```suggestion
```

2024-03-05 05:17 UTC, jetersen commented on src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabSCMNavigator.java
> +
```suggestion
```

2024-03-05 05:17 UTC, jetersen commented on src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabSCMNavigator.java
> +
```suggestion
```

2024-03-05 05:19 UTC, jetersen approved these changes

2024-03-05 05:33 UTC, merged